use crate::Country;
use std::collections::HashMap;

lazy_static! {
    // TODO UPDATE LIST
    pub (crate) static ref COUNTRIES: [Country; 246] = [
        Country { code: "AD", names: vec!["Andorra", "Andorran"] },
        Country { code: "AE", names: vec!["United Arab Emirates", "UAE", "Emirati"] },
        Country { code: "AF", names: vec!["Afghanistan", "Afghan"] },
        Country { code: "AG", names: vec!["Antigua and Barbuda", "Antiguan, Barbudan"] },
        Country { code: "AI", names: vec!["Anguilla", "Anguillian"] },
        Country { code: "AL", names: vec!["Albania", "Albanian"] },
        Country { code: "AM", names: vec!["Armenia", "Armenian"] },
        Country { code: "AN", names: vec!["Netherlands Antilles"] },
        Country { code: "AO", names: vec!["Angola", "Angolan"] },
        Country { code: "AQ", names: vec!["Antarctica", "Antarctican"] },
        Country { code: "AR", names: vec!["Argentina", "Argentine"] },
        Country { code: "AS", names: vec!["American Samoa", "American Samoan"] },
        Country { code: "AT", names: vec!["Austria", "Austrian"] },
        Country { code: "AU", names: vec!["Australia", "Australian"] },
        Country { code: "AW", names: vec!["Aruba", "Aruban"] },
        Country { code: "AX", names: vec!["Åland Islands", "Ålandish"] },
        Country { code: "AZ", names: vec!["Azerbaijan", "Azerbaijani"] },
        Country { code: "BA", names: vec!["Bosnia and Herzegovina", "Bosnian, Herzegovinian"] },
        Country { code: "BB", names: vec!["Barbados", "Barbadian"] },
        Country { code: "BD", names: vec!["Bangladesh", "Bangladeshi"] },
        Country { code: "BE", names: vec!["Belgium", "Belgian"] },
        Country { code: "BF", names: vec!["Burkina Faso", "Burkinabe"] },
        Country { code: "BG", names: vec!["Bulgaria", "Bulgarian"] },
        Country { code: "BH", names: vec!["Bahrain", "Bahraini"] },
        Country { code: "BI", names: vec!["Burundi", "Burundian"] },
        Country { code: "BJ", names: vec!["Benin", "Beninese"] },
        Country { code: "BM", names: vec!["Bermuda", "Bermudian"] },
        Country { code: "BN", names: vec!["Brunei Darussalam", "Bruneian"] },
        Country { code: "BO", names: vec!["Bolivia", "Bolivian"] },
        Country { code: "BR", names: vec!["Brazil", "Brazilian"] },
        Country { code: "BS", names: vec!["Bahamas", "Bahamian"] },
        Country { code: "BT", names: vec!["Bhutan", "Bhutanese"] },
        Country { code: "BV", names: vec!["Bouvet Island"] },
        Country { code: "BW", names: vec!["Botswana", "Motswana"] },
        Country { code: "BY", names: vec!["Belarus", "Belarusian"] },
        Country { code: "BZ", names: vec!["Belize", "Belizean"] },
        Country { code: "CA", names: vec!["Canada", "Canadian"] },
        Country { code: "CC", names: vec!["Cocos (Keeling) Islands", "Cocos Islander"] },
        Country { code: "CD", names: vec!["Congo, The Democratic Republic of the"] },
        Country { code: "CF", names: vec!["Central African Republic", "Central African"] },
        Country { code: "CG", names: vec!["Congo"] },
        Country { code: "CH", names: vec!["Switzerland", "Swiss"] },
        Country { code: "CI", names: vec!["Cote D'Ivoire", "Ivorian"] },
        Country { code: "CK", names: vec!["Cook Islands", "Cook Islander"] },
        Country { code: "CL", names: vec!["Chile", "Chilean"] },
        Country { code: "CM", names: vec!["Cameroon", "Cameroonian"] },
        Country { code: "CN", names: vec!["China", "Chinese"] },
        Country { code: "CO", names: vec!["Colombia", "Colombian"] },
        Country { code: "CR", names: vec!["Costa Rica", "Costa Rican"] },
        Country { code: "CU", names: vec!["Cuba", "Cuban"] },
        Country { code: "CV", names: vec!["Cape Verde", "Cape Verdian"] },
        Country { code: "CX", names: vec!["Christmas Island", "Christmas Islander"] },
        Country { code: "CY", names: vec!["Cyprus", "Cypriot"] },
        Country { code: "CZ", names: vec!["Czechia", "Czech Republic", "Czech"] },
        Country { code: "DE", names: vec!["Germany", "German"] },
        Country { code: "DJ", names: vec!["Djibouti"] },
        Country { code: "DK", names: vec!["Denmark", "Danish"] },
        Country { code: "DM", names: vec!["Dominica"] },
        Country { code: "DO", names: vec!["Dominican Republic"] },
        Country { code: "DZ", names: vec!["Algeria", "Algerian"] },
        Country { code: "EC", names: vec!["Ecuador", "Ecuadorean"] },
        Country { code: "EE", names: vec!["Estonia", "Estonian"] },
        Country { code: "EG", names: vec!["Egypt", "Egyptian"] },
        Country { code: "EH", names: vec!["Western Sahara", "Sahrawi"] },
        Country { code: "ER", names: vec!["Eritrea", "Eritrean"] },
        Country { code: "ES", names: vec!["Spain", "Spanish"] },
        Country { code: "ET", names: vec!["Ethiopia", "Ethiopian"] },
        Country { code: "EU", names: vec!["European Union"] },
        Country { code: "FI", names: vec!["Finland", "Finnish"] },
        Country { code: "FJ", names: vec!["Fiji", "Fijian"] },
        Country { code: "FK", names: vec!["Falkland Islands (Malvinas)", "Falkland Islander"] },
        Country { code: "FM", names: vec!["Micronesia, Federated States of", "Micronesian"] },
        Country { code: "FO", names: vec!["Faroe Islands", "Faroese"] },
        Country { code: "FR", names: vec!["France", "French"] },
        Country { code: "GA", names: vec!["Gabon", "Gabonese"] },
        Country { code: "GB", names: vec!["United Kingdom", "UK", "British"] },
        Country { code: "GD", names: vec!["Grenada", "Grenadian"] },
        Country { code: "GE", names: vec!["Georgia", "Georgian"] },
        Country { code: "GF", names: vec!["French Guiana", "Guianan"] },
        Country { code: "GG", names: vec!["Guernsey"] },
        Country { code: "GH", names: vec!["Ghana", "Ghanaian"] },
        Country { code: "GI", names: vec!["Gibraltar"] },
        Country { code: "GL", names: vec!["Greenland", "Greenlandic"] },
        Country { code: "GM", names: vec!["Gambia", "Gambian"] },
        Country { code: "GN", names: vec!["Guinea", "Guinean"] },
        Country { code: "GP", names: vec!["Guadeloupe", "Guadeloupian"] },
        Country { code: "GQ", names: vec!["Equatorial Guinea", "Equatorial Guinean"] },
        Country { code: "GR", names: vec!["Greece", "Greek"] },
        Country { code: "GS", names: vec!["South Georgia and the South Sandwich Islands", "South Georgian South Sandwich Islander"] },
        Country { code: "GT", names: vec!["Guatemala", "Guatemalan"] },
        Country { code: "GU", names: vec!["Guam", "Guamanian"] },
        Country { code: "GW", names: vec!["Guinea-Bissau", "Guinea-Bissauan"] },
        Country { code: "GY", names: vec!["Guyana", "Guyanese"] },
        Country { code: "HK", names: vec!["Hong Kong", "Hong Konger"] },
        Country { code: "HM", names: vec!["Heard Island and Mcdonald Islands", "Heard and McDonald Islander"] },
        Country { code: "HN", names: vec!["Honduras", "Honduran"] },
        Country { code: "HR", names: vec!["Croatia", "Croatian"] },
        Country { code: "HT", names: vec!["Haiti", "Haitian"] },
        Country { code: "HU", names: vec!["Hungary", "Hungarian"] },
        Country { code: "ID", names: vec!["Indonesia", "Indonesian"] },
        Country { code: "IE", names: vec!["Ireland", "Irish"] },
        Country { code: "IL", names: vec!["Israel", "Israeli"] },
        Country { code: "IM", names: vec!["Isle of Man", "Manx"] },
        Country { code: "IN", names: vec!["India", "Indian"] },
        Country { code: "IO", names: vec!["British Indian Ocean Territory"] },
        Country { code: "IQ", names: vec!["Iraq", "Iraqi"] },
        Country { code: "IR", names: vec!["Iran, Islamic Republic Of", "Iranian"] },
        Country { code: "IS", names: vec!["Iceland", "Icelander"] },
        Country { code: "IT", names: vec!["Italy", "Italian"] },
        Country { code: "JE", names: vec!["Jersey"] },
        Country { code: "JM", names: vec!["Jamaica", "Jamaican"] },
        Country { code: "JO", names: vec!["Jordan", "Jordanian"] },
        Country { code: "JP", names: vec!["Japan", "Japanese"] },
        Country { code: "KE", names: vec!["Kenya", "Kenyan"] },
        Country { code: "KG", names: vec!["Kyrgyzstan", "Kirghiz"] },
        Country { code: "KH", names: vec!["Cambodia", "Cambodian"] },
        Country { code: "KI", names: vec!["Kiribati", "I-Kiribati"] },
        Country { code: "KM", names: vec!["Comoros", "Comoran"] },
        Country { code: "KN", names: vec!["Saint Kitts and Nevis", "Kittitian or Nevisian"] },
        Country { code: "KP", names: vec!["Korea, Democratic People's Republic of", "North Korea", "North Korean", "DPRK"] },
        Country { code: "KR", names: vec!["Korea, Republic of", "South Korea", "South Korean"] },
        Country { code: "KW", names: vec!["Kuwait", "Kuwaiti"] },
        Country { code: "KY", names: vec!["Cayman Islands", "Caymanian"] },
        Country { code: "KZ", names: vec!["Kazakhstan", "Kazakhstani"] },
        Country { code: "LA", names: vec!["Lao People's Democratic Republic", "Laotian"] },
        Country { code: "LB", names: vec!["Lebanon", "Lebanese"] },
        Country { code: "LC", names: vec!["Saint Lucia", "Saint Lucian"] },
        Country { code: "LI", names: vec!["Liechtenstein", "Liechtensteiner"] },
        Country { code: "LK", names: vec!["Sri Lanka", "Sri Lankan"] },
        Country { code: "LR", names: vec!["Liberia", "Liberian"] },
        Country { code: "LS", names: vec!["Lesotho", "Mosotho"] },
        Country { code: "LT", names: vec!["Lithuania", "Lithuanian"] },
        Country { code: "LU", names: vec!["Luxembourg", "Luxembourger"] },
        Country { code: "LV", names: vec!["Latvia", "Latvian"] },
        Country { code: "LY", names: vec!["Libyan Arab Jamahiriya", "Libyan"] },
        Country { code: "MA", names: vec!["Morocco", "Moroccan"] },
        Country { code: "MC", names: vec!["Monaco", "Monegasque"] },
        Country { code: "MD", names: vec!["Moldova, Republic of", "Moldovan"] },
        Country { code: "ME", names: vec!["Montenegro", "Montenegrin"] },
        Country { code: "MG", names: vec!["Madagascar", "Malagasy"] },
        Country { code: "MH", names: vec!["Marshall Islands", "Marshallese"] },
        Country { code: "MK", names: vec!["Republic of North Macedonia", "North Macedonia", "Macedonia, The Former Yugoslav Republic of", "Macedonian"] },
        Country { code: "ML", names: vec!["Mali", "Malian"] },
        Country { code: "MM", names: vec!["Myanmar", "Burma", "Burmese"] },
        Country { code: "MN", names: vec!["Mongolia", "Mongolian"] },
        Country { code: "MO", names: vec!["Macao", "Macau", "Macanese"] },
        Country { code: "MP", names: vec!["Northern Mariana Islands"] },
        Country { code: "MQ", names: vec!["Martinique"] },
        Country { code: "MR", names: vec!["Mauritania", "Mauritanian"] },
        Country { code: "MS", names: vec!["Montserrat", "Montserratian"] },
        Country { code: "MT", names: vec!["Malta", "Maltese"] },
        Country { code: "MU", names: vec!["Mauritius", "Mauritian"] },
        Country { code: "MV", names: vec!["Maldives", "Maldivan"] },
        Country { code: "MW", names: vec!["Malawi", "Malawian"] },
        Country { code: "MX", names: vec!["Mexico", "Mexican"] },
        Country { code: "MY", names: vec!["Malaysia", "Malaysian"] },
        Country { code: "MZ", names: vec!["Mozambique", "Mozambican"] },
        Country { code: "NA", names: vec!["Namibia", "Namibian"] },
        Country { code: "NC", names: vec!["New Caledonia", "New Caledonian"] },
        Country { code: "NE", names: vec!["Niger", "Nigerien"] },
        Country { code: "NF", names: vec!["Norfolk Island", "Norfolk Islander"] },
        Country { code: "NG", names: vec!["Nigeria", "Nigerian"] },
        Country { code: "NI", names: vec!["Nicaragua", "Nicaraguan"] },
        Country { code: "NL", names: vec!["Netherlands", "Dutch"] },
        Country { code: "NO", names: vec!["Norway", "Norwegian"] },
        Country { code: "NP", names: vec!["Nepal", "Nepalese"] },
        Country { code: "NR", names: vec!["Nauru", "Nauruan"] },
        Country { code: "NU", names: vec!["Niue", "Niuean"] },
        Country { code: "NZ", names: vec!["New Zealand", "New Zealander"] },
        Country { code: "OM", names: vec!["Oman", "Omani"] },
        Country { code: "PA", names: vec!["Panama", "Panamanian"] },
        Country { code: "PE", names: vec!["Peru", "Peruvian"] },
        Country { code: "PF", names: vec!["French Polynesia", "French Polynesian"] },
        Country { code: "PG", names: vec!["Papua New Guinea", "Papua New Guinean"] },
        Country { code: "PH", names: vec!["Philippines", "Filipino"] },
        Country { code: "PK", names: vec!["Pakistan", "Pakistani"] },
        Country { code: "PL", names: vec!["Poland", "Polish"] },
        Country { code: "PM", names: vec!["Saint Pierre and Miquelon"] },
        Country { code: "PN", names: vec!["Pitcairn", "Pitcairn Islander"] },
        Country { code: "PR", names: vec!["Puerto Rico", "Puerto Rican"] },
        Country { code: "PS", names: vec!["Palestinian Territory, Occupied", "Palestine", "Palestinian"] },
        Country { code: "PT", names: vec!["Portugal", "Portuguese"] },
        Country { code: "PW", names: vec!["Palau", "Palauan"] },
        Country { code: "PY", names: vec!["Paraguay", "Paraguayan"] },
        Country { code: "QA", names: vec!["Qatar", "Qatari"] },
        Country { code: "RE", names: vec!["Reunion"] },
        Country { code: "RO", names: vec!["Romania", "Romanian"] },
        Country { code: "RS", names: vec!["Serbia", "Serbian"] },
        Country { code: "RU", names: vec!["Russian Federation", "Russian"] },
        Country { code: "RW", names: vec!["Rwanda", "Rwandan"] },
        Country { code: "SA", names: vec!["Saudi Arabia", "Saudi Arabian"] },
        Country { code: "SB", names: vec!["Solomon Islands", "Solomon Islander"] },
        Country { code: "SC", names: vec!["Seychelles", "Seychellois"] },
        Country { code: "SD", names: vec!["Sudan", "Sudanese"] },
        Country { code: "SE", names: vec!["Sweden", "Swedish"] },
        Country { code: "SG", names: vec!["Singapore", "Singaporean"] },
        Country { code: "SH", names: vec!["Saint Helena", "Saint Helenian"] },
        Country { code: "SI", names: vec!["Slovenia", "Slovene"] },
        Country { code: "SJ", names: vec!["Svalbard and Jan Mayen"] },
        Country { code: "SK", names: vec!["Slovakia", "Slovak"] },
        Country { code: "SL", names: vec!["Sierra Leone", "Sierra Leonean"] },
        Country { code: "SM", names: vec!["San Marino", "Sammarinese"] },
        Country { code: "SN", names: vec!["Senegal", "Senegalese"] },
        Country { code: "SO", names: vec!["Somalia", "Somali"] },
        Country { code: "SR", names: vec!["Suriname", "Surinamer"] },
        Country { code: "ST", names: vec!["Sao Tome and Principe", "Sao Tomean"] },
        Country { code: "SV", names: vec!["El Salvador", "Salvadoran"] },
        Country { code: "SY", names: vec!["Syrian Arab Republic", "Syrian"] },
        Country { code: "SZ", names: vec!["Swaziland", "Swazi"] },
        Country { code: "TC", names: vec!["Turks and Caicos Islands", "Turks and Caicos Islander"] },
        Country { code: "TD", names: vec!["Chad", "Chadian"] },
        Country { code: "TF", names: vec!["French Southern Territories"] },
        Country { code: "TG", names: vec!["Togo", "Togolese"] },
        Country { code: "TH", names: vec!["Thailand", "Thai"] },
        Country { code: "TJ", names: vec!["Tajikistan", "Tadzhik"] },
        Country { code: "TK", names: vec!["Tokelau", "Tokelauan"] },
        Country { code: "TL", names: vec!["Timor-Leste", "East Timorese"] },
        Country { code: "TM", names: vec!["Turkmenistan", "Turkmen"] },
        Country { code: "TN", names: vec!["Tunisia", "Tunisian"] },
        Country { code: "TO", names: vec!["Tonga", "Tongan"] },
        Country { code: "TR", names: vec!["Turkey", "Turkish"] },
        Country { code: "TT", names: vec!["Trinidad and Tobago", "Trinidadian"] },
        Country { code: "TV", names: vec!["Tuvalu", "Tuvaluan"] },
        Country { code: "TW", names: vec!["Taiwan", "Taiwanese"] },
        Country { code: "TZ", names: vec!["Tanzania, United Republic of", "Tanzanian"] },
        Country { code: "UA", names: vec!["Ukraine", "Ukrainian"] },
        Country { code: "UG", names: vec!["Uganda", "Ugandan"] },
        Country { code: "UM", names: vec!["United States Minor Outlying Islands"] },
        Country { code: "US", names: vec!["United States", "USA", "American"] },
        Country { code: "UY", names: vec!["Uruguay", "Uruguayan"] },
        Country { code: "UZ", names: vec!["Uzbekistan", "Uzbekistani"] },
        Country { code: "VA", names: vec!["Holy See (Vatican City State)", "Vatican"] },
        Country { code: "VC", names: vec!["Saint Vincent and the Grenadines", "Saint Vincentian"] },
        Country { code: "VE", names: vec!["Venezuela", "Venezuelan"] },
        Country { code: "VG", names: vec!["Virgin Islands, British"] },
        Country { code: "VI", names: vec!["Virgin Islands, U.S."] },
        Country { code: "VN", names: vec!["Vietnam", "Viet Nam", "Vietnamese"] },
        Country { code: "VU", names: vec!["Vanuatu", "Ni-Vanuatu"] },
        Country { code: "WF", names: vec!["Wallis and Futuna", "Wallis and Futuna Islander"] },
        Country { code: "WS", names: vec!["Samoa", "Samoan"] },
        Country { code: "XK", names: vec!["Kosovo", "Kosovar"] },
        Country { code: "YE", names: vec!["Yemen", "Yemeni"] },
        Country { code: "YT", names: vec!["Mayotte", "Mahoran"] },
        Country { code: "ZA", names: vec!["South Africa", "South African"] },
        Country { code: "ZM", names: vec!["Zambia", "Zambian"] },
        Country { code: "ZW", names: vec!["Zimbabwe", "Zimbabwean"] },
    ];

    pub (crate) static ref COUNTRIES_MAP: HashMap<&'static str, &'static Country> =
        COUNTRIES.iter().map(|country| (country.code, country)).collect();
}
