use std::collections::HashMap;

lazy_static!{
    pub static ref COUNTRIES: HashMap<&'static str, Vec<&'static str>> = [
        ("AD", vec!["Andorra", "Andorran"]),
        ("AE", vec!["United Arab Emirates", "UAE", "Emirati"]),
        ("AF", vec!["Afghanistan", "Afghan"]),
        ("AG", vec!["Antigua and Barbuda", "Antiguan, Barbudan"]),
        ("AI", vec!["Anguilla", "Anguillian"]),
        ("AL", vec!["Albania", "Albanian"]),
        ("AM", vec!["Armenia", "Armenian"]),
        ("AN", vec!["Netherlands Antilles"]),
        ("AO", vec!["Angola", "Angolan"]),
        ("AQ", vec!["Antarctica", "Antarctican"]),
        ("AR", vec!["Argentina", "Argentine"]),
        ("AS", vec!["American Samoa", "American Samoan"]),
        ("AT", vec!["Austria", "Austrian"]),
        ("AU", vec!["Australia", "Australian"]),
        ("AW", vec!["Aruba", "Aruban"]),
        ("AX", vec!["Åland Islands", "Ålandish"]),
        ("AZ", vec!["Azerbaijan", "Azerbaijani"]),
        ("BA", vec!["Bosnia and Herzegovina", "Bosnian, Herzegovinian"]),
        ("BB", vec!["Barbados", "Barbadian"]),
        ("BD", vec!["Bangladesh", "Bangladeshi"]),
        ("BE", vec!["Belgium", "Belgian"]),
        ("BF", vec!["Burkina Faso", "Burkinabe"]),
        ("BG", vec!["Bulgaria", "Bulgarian"]),
        ("BH", vec!["Bahrain", "Bahraini"]),
        ("BI", vec!["Burundi", "Burundian"]),
        ("BJ", vec!["Benin", "Beninese"]),
        ("BM", vec!["Bermuda", "Bermudian"]),
        ("BN", vec!["Brunei Darussalam", "Bruneian"]),
        ("BO", vec!["Bolivia", "Bolivian"]),
        ("BR", vec!["Brazil", "Brazilian"]),
        ("BS", vec!["Bahamas", "Bahamian"]),
        ("BT", vec!["Bhutan", "Bhutanese"]),
        ("BV", vec!["Bouvet Island"]),
        ("BW", vec!["Botswana", "Motswana"]),
        ("BY", vec!["Belarus", "Belarusian"]),
        ("BZ", vec!["Belize", "Belizean"]),
        ("CA", vec!["Canada", "Canadian"]),
        ("CC", vec!["Cocos (Keeling) Islands", "Cocos Islander"]),
        ("CD", vec!["Congo, The Democratic Republic of the"]),
        ("CF", vec!["Central African Republic", "Central African"]),
        ("CG", vec!["Congo"]),
        ("CH", vec!["Switzerland", "Swiss"]),
        ("CI", vec!["Cote D'Ivoire", "Ivorian"]),
        ("CK", vec!["Cook Islands", "Cook Islander"]),
        ("CL", vec!["Chile", "Chilean"]),
        ("CM", vec!["Cameroon", "Cameroonian"]),
        ("CN", vec!["China", "Chinese"]),
        ("CO", vec!["Colombia", "Colombian"]),
        ("CR", vec!["Costa Rica", "Costa Rican"]),
        ("CU", vec!["Cuba", "Cuban"]),
        ("CV", vec!["Cape Verde", "Cape Verdian"]),
        ("CX", vec!["Christmas Island", "Christmas Islander"]),
        ("CY", vec!["Cyprus", "Cypriot"]),
        ("CZ", vec!["Czechia", "Czech Republic", "Czech"]),
        ("DE", vec!["Germany", "German"]),
        ("DJ", vec!["Djibouti"]),
        ("DK", vec!["Denmark", "Danish"]),
        ("DM", vec!["Dominica"]),
        ("DO", vec!["Dominican Republic"]),
        ("DZ", vec!["Algeria", "Algerian"]),
        ("EC", vec!["Ecuador", "Ecuadorean"]),
        ("EE", vec!["Estonia", "Estonian"]),
        ("EG", vec!["Egypt", "Egyptian"]),
        ("EH", vec!["Western Sahara", "Sahrawi"]),
        ("ER", vec!["Eritrea", "Eritrean"]),
        ("ES", vec!["Spain", "Spanish"]),
        ("ET", vec!["Ethiopia", "Ethiopian"]),
        ("EU", vec!["European Union"]),
        ("FI", vec!["Finland", "Finnish"]),
        ("FJ", vec!["Fiji", "Fijian"]),
        ("FK", vec!["Falkland Islands (Malvinas)", "Falkland Islander"]),
        ("FM", vec!["Micronesia, Federated States of", "Micronesian"]),
        ("FO", vec!["Faroe Islands", "Faroese"]),
        ("FR", vec!["France", "French"]),
        ("GA", vec!["Gabon", "Gabonese"]),
        ("GB", vec!["United Kingdom", "UK", "British"]),
        ("GD", vec!["Grenada", "Grenadian"]),
        ("GE", vec!["Georgia", "Georgian"]),
        ("GF", vec!["French Guiana", "Guianan"]),
        ("GG", vec!["Guernsey"]),
        ("GH", vec!["Ghana", "Ghanaian"]),
        ("GI", vec!["Gibraltar"]),
        ("GL", vec!["Greenland", "Greenlandic"]),
        ("GM", vec!["Gambia", "Gambian"]),
        ("GN", vec!["Guinea", "Guinean"]),
        ("GP", vec!["Guadeloupe", "Guadeloupian"]),
        ("GQ", vec!["Equatorial Guinea", "Equatorial Guinean"]),
        ("GR", vec!["Greece", "Greek"]),
        ("GS", vec!["South Georgia and the South Sandwich Islands", "South Georgian South Sandwich Islander"]),
        ("GT", vec!["Guatemala", "Guatemalan"]),
        ("GU", vec!["Guam", "Guamanian"]),
        ("GW", vec!["Guinea-Bissau", "Guinea-Bissauan"]),
        ("GY", vec!["Guyana", "Guyanese"]),
        ("HK", vec!["Hong Kong", "Hong Konger"]),
        ("HM", vec!["Heard Island and Mcdonald Islands", "Heard and McDonald Islander"]),
        ("HN", vec!["Honduras", "Honduran"]),
        ("HR", vec!["Croatia", "Croatian"]),
        ("HT", vec!["Haiti", "Haitian"]),
        ("HU", vec!["Hungary", "Hungarian"]),
        ("ID", vec!["Indonesia", "Indonesian"]),
        ("IE", vec!["Ireland", "Irish"]),
        ("IL", vec!["Israel", "Israeli"]),
        ("IM", vec!["Isle of Man", "Manx"]),
        ("IN", vec!["India", "Indian"]),
        ("IO", vec!["British Indian Ocean Territory"]),
        ("IQ", vec!["Iraq", "Iraqi"]),
        ("IR", vec!["Iran, Islamic Republic Of", "Iranian"]),
        ("IS", vec!["Iceland", "Icelander"]),
        ("IT", vec!["Italy", "Italian"]),
        ("JE", vec!["Jersey"]),
        ("JM", vec!["Jamaica", "Jamaican"]),
        ("JO", vec!["Jordan", "Jordanian"]),
        ("JP", vec!["Japan", "Japanese"]),
        ("KE", vec!["Kenya", "Kenyan"]),
        ("KG", vec!["Kyrgyzstan", "Kirghiz"]),
        ("KH", vec!["Cambodia", "Cambodian"]),
        ("KI", vec!["Kiribati", "I-Kiribati"]),
        ("KM", vec!["Comoros", "Comoran"]),
        ("KN", vec!["Saint Kitts and Nevis", "Kittitian or Nevisian"]),
        ("KP", vec!["Korea, Democratic People's Republic of", "North Korea", "North Korean", "DPRK"]),
        ("KR", vec!["Korea, Republic of", "South Korea", "South Korean"]),
        ("KW", vec!["Kuwait", "Kuwaiti"]),
        ("KY", vec!["Cayman Islands", "Caymanian"]),
        ("KZ", vec!["Kazakhstan", "Kazakhstani"]),
        ("LA", vec!["Lao People's Democratic Republic", "Laotian"]),
        ("LB", vec!["Lebanon", "Lebanese"]),
        ("LC", vec!["Saint Lucia", "Saint Lucian"]),
        ("LI", vec!["Liechtenstein", "Liechtensteiner"]),
        ("LK", vec!["Sri Lanka", "Sri Lankan"]),
        ("LR", vec!["Liberia", "Liberian"]),
        ("LS", vec!["Lesotho", "Mosotho"]),
        ("LT", vec!["Lithuania", "Lithuanian"]),
        ("LU", vec!["Luxembourg", "Luxembourger"]),
        ("LV", vec!["Latvia", "Latvian"]),
        ("LY", vec!["Libyan Arab Jamahiriya", "Libyan"]),
        ("MA", vec!["Morocco", "Moroccan"]),
        ("MC", vec!["Monaco", "Monegasque"]),
        ("MD", vec!["Moldova, Republic of", "Moldovan"]),
        ("ME", vec!["Montenegro", "Montenegrin"]),
        ("MG", vec!["Madagascar", "Malagasy"]),
        ("MH", vec!["Marshall Islands", "Marshallese"]),
        ("MK", vec!["Republic of North Macedonia", "North Macedonia", "Macedonia, The Former Yugoslav Republic of", "Macedonian"]),
        ("ML", vec!["Mali", "Malian"]),
        ("MM", vec!["Myanmar", "Burma", "Burmese"]),
        ("MN", vec!["Mongolia", "Mongolian"]),
        ("MO", vec!["Macao", "Macau", "Macanese"]),
        ("MP", vec!["Northern Mariana Islands"]),
        ("MQ", vec!["Martinique"]),
        ("MR", vec!["Mauritania", "Mauritanian"]),
        ("MS", vec!["Montserrat", "Montserratian"]),
        ("MT", vec!["Malta", "Maltese"]),
        ("MU", vec!["Mauritius", "Mauritian"]),
        ("MV", vec!["Maldives", "Maldivan"]),
        ("MW", vec!["Malawi", "Malawian"]),
        ("MX", vec!["Mexico", "Mexican"]),
        ("MY", vec!["Malaysia", "Malaysian"]),
        ("MZ", vec!["Mozambique", "Mozambican"]),
        ("NA", vec!["Namibia", "Namibian"]),
        ("NC", vec!["New Caledonia", "New Caledonian"]),
        ("NE", vec!["Niger", "Nigerien"]),
        ("NF", vec!["Norfolk Island", "Norfolk Islander"]),
        ("NG", vec!["Nigeria", "Nigerian"]),
        ("NI", vec!["Nicaragua", "Nicaraguan"]),
        ("NL", vec!["Netherlands", "Dutch"]),
        ("NO", vec!["Norway", "Norwegian"]),
        ("NP", vec!["Nepal", "Nepalese"]),
        ("NR", vec!["Nauru", "Nauruan"]),
        ("NU", vec!["Niue", "Niuean"]),
        ("NZ", vec!["New Zealand", "New Zealander"]),
        ("OM", vec!["Oman", "Omani"]),
        ("PA", vec!["Panama", "Panamanian"]),
        ("PE", vec!["Peru", "Peruvian"]),
        ("PF", vec!["French Polynesia", "French Polynesian"]),
        ("PG", vec!["Papua New Guinea", "Papua New Guinean"]),
        ("PH", vec!["Philippines", "Filipino"]),
        ("PK", vec!["Pakistan", "Pakistani"]),
        ("PL", vec!["Poland", "Polish"]),
        ("PM", vec!["Saint Pierre and Miquelon"]),
        ("PN", vec!["Pitcairn", "Pitcairn Islander"]),
        ("PR", vec!["Puerto Rico", "Puerto Rican"]),
        ("PS", vec!["Palestinian Territory, Occupied", "Palestine", "Palestinian"]),
        ("PT", vec!["Portugal", "Portuguese"]),
        ("PW", vec!["Palau", "Palauan"]),
        ("PY", vec!["Paraguay", "Paraguayan"]),
        ("QA", vec!["Qatar", "Qatari"]),
        ("RE", vec!["Reunion"]),
        ("RO", vec!["Romania", "Romanian"]),
        ("RS", vec!["Serbia", "Serbian"]),
        ("RU", vec!["Russian Federation", "Russian"]),
        ("RW", vec!["Rwanda", "Rwandan"]),
        ("SA", vec!["Saudi Arabia", "Saudi Arabian"]),
        ("SB", vec!["Solomon Islands", "Solomon Islander"]),
        ("SC", vec!["Seychelles", "Seychellois"]),
        ("SD", vec!["Sudan", "Sudanese"]),
        ("SE", vec!["Sweden", "Swedish"]),
        ("SG", vec!["Singapore", "Singaporean"]),
        ("SH", vec!["Saint Helena", "Saint Helenian"]),
        ("SI", vec!["Slovenia", "Slovene"]),
        ("SJ", vec!["Svalbard and Jan Mayen"]),
        ("SK", vec!["Slovakia", "Slovak"]),
        ("SL", vec!["Sierra Leone", "Sierra Leonean"]),
        ("SM", vec!["San Marino", "Sammarinese"]),
        ("SN", vec!["Senegal", "Senegalese"]),
        ("SO", vec!["Somalia", "Somali"]),
        ("SR", vec!["Suriname", "Surinamer"]),
        ("ST", vec!["Sao Tome and Principe", "Sao Tomean"]),
        ("SV", vec!["El Salvador", "Salvadoran"]),
        ("SY", vec!["Syrian Arab Republic", "Syrian"]),
        ("SZ", vec!["Swaziland", "Swazi"]),
        ("TC", vec!["Turks and Caicos Islands", "Turks and Caicos Islander"]),
        ("TD", vec!["Chad", "Chadian"]),
        ("TF", vec!["French Southern Territories"]),
        ("TG", vec!["Togo", "Togolese"]),
        ("TH", vec!["Thailand", "Thai"]),
        ("TJ", vec!["Tajikistan", "Tadzhik"]),
        ("TK", vec!["Tokelau", "Tokelauan"]),
        ("TL", vec!["Timor-Leste", "East Timorese"]),
        ("TM", vec!["Turkmenistan", "Turkmen"]),
        ("TN", vec!["Tunisia", "Tunisian"]),
        ("TO", vec!["Tonga", "Tongan"]),
        ("TR", vec!["Turkey", "Turkish"]),
        ("TT", vec!["Trinidad and Tobago", "Trinidadian"]),
        ("TV", vec!["Tuvalu", "Tuvaluan"]),
        ("TW", vec!["Taiwan", "Taiwanese"]),
        ("TZ", vec!["Tanzania, United Republic of", "Tanzanian"]),
        ("UA", vec!["Ukraine", "Ukrainian"]),
        ("UG", vec!["Uganda", "Ugandan"]),
        ("UM", vec!["United States Minor Outlying Islands"]),
        ("US", vec!["United States", "USA", "American"]),
        ("UY", vec!["Uruguay", "Uruguayan"]),
        ("UZ", vec!["Uzbekistan", "Uzbekistani"]),
        ("VA", vec!["Holy See (Vatican City State)", "Vatican"]),
        ("VC", vec!["Saint Vincent and the Grenadines", "Saint Vincentian"]),
        ("VE", vec!["Venezuela", "Venezuelan"]),
        ("VG", vec!["Virgin Islands, British"]),
        ("VI", vec!["Virgin Islands, U.S."]),
        ("VN", vec!["Vietnam", "Viet Nam", "Vietnamese"]),
        ("VU", vec!["Vanuatu", "Ni-Vanuatu"]),
        ("WF", vec!["Wallis and Futuna", "Wallis and Futuna Islander"]),
        ("WS", vec!["Samoa", "Samoan"]),
        ("XK", vec!["Kosovo", "Kosovar"]),
        ("YE", vec!["Yemen", "Yemeni"]),
        ("YT", vec!["Mayotte", "Mahoran"]),
        ("ZA", vec!["South Africa", "South African"]),
        ("ZM", vec!["Zambia", "Zambian"]),
        ("ZW", vec!["Zimbabwe", "Zimbabwean"]),
    ].iter().cloned().collect();
}


