use crate::Country;
use once_cell::sync::Lazy;
use std::collections::HashMap;

// TODO UPDATE LIST
pub(crate) static COUNTRIES: Lazy<Vec<Country>> = Lazy::new(|| {
    vec![
        ("AC", &["Ascension Island", "Ascension Islander"]),
        ("AD", &["Andorra", "Andorran"]),
        ("AE", &["United Arab Emirates", "UAE", "Emirati"]),
        ("AF", &["Afghanistan", "Afghan"]),
        ("AG", &["Antigua & Barbuda", "Antiguan", "Barbudan"]),
        ("AI", &["Anguilla", "Anguillian"]),
        ("AL", &["Albania", "Albanian"]),
        ("AM", &["Armenia", "Armenian"]),
        ("AN", &["Netherlands Antilles"]), // Dissolved 2010, kept for legacy compatibility
        ("AO", &["Angola", "Angolan"]),
        ("AQ", &["Antarctica", "Antarctican"]),
        ("AR", &["Argentina", "Argentine"]),
        ("AS", &["American Samoa", "American Samoan"]),
        ("AT", &["Austria", "Austrian"]),
        ("AU", &["Australia", "Australian"]),
        ("AW", &["Aruba", "Aruban"]),
        ("AX", &["Åland Islands", "Ålandish"]),
        ("AZ", &["Azerbaijan", "Azerbaijani"]),
        ("BA", &["Bosnia & Herzegovina", "Bosnian, Herzegovinian"]),
        ("BB", &["Barbados", "Barbadian"]),
        ("BD", &["Bangladesh", "Bangladeshi"]),
        ("BE", &["Belgium", "Belgian"]),
        ("BF", &["Burkina Faso", "Burkinabe"]),
        ("BG", &["Bulgaria", "Bulgarian"]),
        ("BH", &["Bahrain", "Bahraini"]),
        ("BI", &["Burundi", "Burundian"]),
        ("BJ", &["Benin", "Beninese"]),
        ("BL", &["Saint Barthélemy", "Barthélemois"]),
        ("BM", &["Bermuda", "Bermudian"]),
        ("BN", &["Brunei", "Brunei Darussalam", "Bruneian"]),
        (
            "BO",
            &["Bolivia", "Plurinational State of Bolivia", "Bolivian"],
        ),
        (
            "BQ",
            &[
                "Caribbean Netherlands",
                "Bonaire, Sint Eustatius and Saba",
                "BES Islands",
                "Caribbean Dutch",
            ],
        ),
        ("BR", &["Brazil", "Brazilian"]),
        ("BS", &["Bahamas", "Bahamian"]),
        ("BT", &["Bhutan", "Bhutanese"]),
        ("BV", &["Bouvet Island", "Bouvet Islander"]),
        ("BW", &["Botswana", "Motswana"]),
        ("BY", &["Belarus", "Belarusian"]),
        ("BZ", &["Belize", "Belizean"]),
        ("CA", &["Canada", "Canadian"]),
        (
            "CC",
            &[
                "Cocos Islands",
                "Cocos Keeling Islands",
                "Cocos (Keeling) Islands",
                "Territory of Cocos (Keeling) Islands",
                "Cocos Islander",
            ],
        ),
        (
            "CD",
            &[
                "Congo-Kinshasa",
                "Democratic Republic of the Congo",
                "Congo",
                "Congo, The Democratic Republic of the",
                "Congolese",
                "Congolese (Kinshasa)",
            ],
        ),
        ("CF", &["Central African Republic", "Central African"]),
        (
            "CG",
            &[
                "Congo-Brazzaville",
                "Republic of the Congo",
                "Congolese (Brazzaville)",
            ],
        ),
        ("CH", &["Switzerland", "Swiss"]),
        ("CI", &["Côte d'Ivoire", "Cote D'Ivoire", "Ivorian"]),
        ("CK", &["Cook Islands", "Cook Islander"]),
        ("CL", &["Chile", "Chilean"]),
        ("CM", &["Cameroon", "Cameroonian"]),
        ("CN", &["China", "Chinese"]),
        ("CO", &["Colombia", "Colombian"]),
        ("CP", &["Clipperton Island", "Clipperton Islander"]),
        ("CQ", &["Sark", "Sercquiais"]),
        ("CR", &["Costa Rica", "Costa Rican"]),
        ("CU", &["Cuba", "Cuban"]),
        ("CV", &["Cape Verde", "Cape Verdean"]),
        ("CW", &["Curaçao", "Curacao", "Curaçaoan"]),
        ("CX", &["Christmas Island", "Christmas Islander"]),
        ("CY", &["Cyprus", "Cypriot"]),
        ("CZ", &["Czechia", "Czech Republic", "Czech"]),
        ("DE", &["Germany", "German"]),
        ("DG", &["Diego Garcia", "Diego Garcian"]),
        ("DJ", &["Djibouti", "Djiboutian"]),
        ("DK", &["Denmark", "Danish"]),
        ("DM", &["Dominica", "Dominican"]),
        ("DO", &["Dominican Republic", "Dominican"]),
        ("DZ", &["Algeria", "Algerian"]),
        (
            "EA",
            &["Ceuta & Melilla", "Ceutí, Melillense"],
        ),
        ("EC", &["Ecuador", "Ecuadorean"]),
        ("EE", &["Estonia", "Estonian"]),
        ("EG", &["Egypt", "Egyptian"]),
        ("EH", &["Western Sahara", "Sahrawi"]),
        ("ER", &["Eritrea", "Eritrean"]),
        ("ES", &["Spain", "Spanish"]),
        ("ET", &["Ethiopia", "Ethiopian"]),
        ("EU", &["European Union", "European"]),
        ("FI", &["Finland", "Finnish"]),
        ("FJ", &["Fiji", "Fijian"]),
        (
            "FK",
            &[
                "Falkland Islands",
                "Falkland Islands (Malvinas)",
                "Falkland Islander",
            ],
        ),
        (
            "FM",
            &[
                "Micronesia",
                "Federated States of Micronesia",
                "Micronesian",
            ],
        ),
        ("FO", &["Faroe Islands", "Faroese"]),
        ("FR", &["France", "French"]),
        ("GA", &["Gabon", "Gabonese"]),
        ("GB", &["United Kingdom", "UK", "British"]),
        ("GD", &["Grenada", "Grenadian"]),
        ("GE", &["Georgia", "Georgian"]),
        ("GF", &["French Guiana", "Guianan"]),
        ("GG", &["Guernsey", "Guernsey person"]),
        ("GH", &["Ghana", "Ghanaian"]),
        ("GI", &["Gibraltar", "Gibraltarian"]),
        ("GL", &["Greenland", "Greenlandic"]),
        ("GM", &["Gambia", "Gambian"]),
        ("GN", &["Guinea", "Guinean"]),
        ("GP", &["Guadeloupe", "Guadeloupian"]),
        ("GQ", &["Equatorial Guinea", "Equatorial Guinean"]),
        ("GR", &["Greece", "Greek"]),
        (
            "GS",
            &[
                "South Georgia & South Sandwich Islands",
                "South Georgian South Sandwich Islander",
            ],
        ),
        ("GT", &["Guatemala", "Guatemalan"]),
        ("GU", &["Guam", "Guamanian"]),
        ("GW", &["Guinea-Bissau", "Guinea-Bissauan"]),
        ("GY", &["Guyana", "Guyanese"]),
        ("HK", &["Hong Kong", "Hong Kong SAR China", "Hong Konger"]),
        (
            "HM",
            &[
                "Heard & McDonald Islands",
                "Heard and McDonald Islander",
            ],
        ),
        ("HN", &["Honduras", "Honduran"]),
        ("HR", &["Croatia", "Croatian"]),
        ("HT", &["Haiti", "Haitian"]),
        ("HU", &["Hungary", "Hungarian"]),
        ("IC", &["Canary Islands", "Canarian"]),
        ("ID", &["Indonesia", "Indonesian"]),
        ("IE", &["Ireland", "Irish"]),
        ("IL", &["Israel", "Israeli"]),
        ("IM", &["Isle of Man", "Manx"]),
        ("IN", &["India", "Indian"]),
        ("IO", &["British Indian Ocean Territory", "BIOT Islander"]),
        ("IQ", &["Iraq", "Iraqi"]),
        ("IR", &["Iran", "Iranian"]),
        ("IS", &["Iceland", "Icelander"]),
        ("IT", &["Italy", "Italian"]),
        ("JE", &["Jersey", "Jersey person"]),
        ("JM", &["Jamaica", "Jamaican"]),
        ("JO", &["Jordan", "Jordanian"]),
        ("JP", &["Japan", "Japanese"]),
        ("KE", &["Kenya", "Kenyan"]),
        ("KG", &["Kyrgyzstan", "Kirghiz"]),
        ("KH", &["Cambodia", "Cambodian"]),
        ("KI", &["Kiribati", "I-Kiribati"]),
        ("KM", &["Comoros", "Comoran"]),
        (
            "KN",
            &[
                "Saint Kitts & Nevis",
                "Kittitian or Nevisian",
            ],
        ),
        (
            "KP",
            &[
                "North Korea",
                "Korea, Democratic People's Republic of",
                "North Korean",
                "DPRK",
            ],
        ),
        ("KR", &["South Korea", "Korea, Republic of", "South Korean"]),
        ("KW", &["Kuwait", "Kuwaiti"]),
        ("KY", &["Cayman Islands", "Caymanian"]),
        ("KZ", &["Kazakhstan", "Kazakhstani"]),
        (
            "LA",
            &["Laos", "Lao People's Democratic Republic", "Laotian"],
        ),
        ("LB", &["Lebanon", "Lebanese"]),
        ("LC", &["Saint Lucia", "Saint Lucian"]),
        ("LI", &["Liechtenstein", "Liechtensteiner"]),
        ("LK", &["Sri Lanka", "Sri Lankan"]),
        ("LR", &["Liberia", "Liberian"]),
        ("LS", &["Lesotho", "Mosotho"]),
        ("LT", &["Lithuania", "Lithuanian"]),
        ("LU", &["Luxembourg", "Luxembourger"]),
        ("LV", &["Latvia", "Latvian"]),
        ("LY", &["Libya", "Libyan"]),
        ("MA", &["Morocco", "Moroccan"]),
        ("MC", &["Monaco", "Monegasque"]),
        ("MD", &["Moldova", "Moldovan"]),
        ("ME", &["Montenegro", "Montenegrin"]),
        ("MF", &["Saint Martin", "Saint-Martinois"]),
        ("MG", &["Madagascar", "Malagasy"]),
        ("MH", &["Marshall Islands", "Marshallese"]),
        (
            "MK",
            &[
                "North Macedonia",
                "Macedonia, The Former Yugoslav Republic of",
                "Macedonian",
            ],
        ),
        ("ML", &["Mali", "Malian"]),
        ("MM", &["Myanmar", "Myanmar (Burma)", "Burma", "Burmese"]),
        ("MN", &["Mongolia", "Mongolian"]),
        ("MO", &["Macao", "Macao SAR China", "Macau", "Macanese"]),
        ("MP", &["Northern Mariana Islands", "Northern Marianan"]),
        ("MQ", &["Martinique", "Martinican"]),
        ("MR", &["Mauritania", "Mauritanian"]),
        ("MS", &["Montserrat", "Montserratian"]),
        ("MT", &["Malta", "Maltese"]),
        ("MU", &["Mauritius", "Mauritian"]),
        ("MV", &["Maldives", "Maldivan"]),
        ("MW", &["Malawi", "Malawian"]),
        ("MX", &["Mexico", "Mexican"]),
        ("MY", &["Malaysia", "Malaysian"]),
        ("MZ", &["Mozambique", "Mozambican"]),
        ("NA", &["Namibia", "Namibian"]),
        ("NC", &["New Caledonia", "New Caledonian"]),
        ("NE", &["Niger", "Nigerien"]),
        ("NF", &["Norfolk Island", "Norfolk Islander"]),
        ("NG", &["Nigeria", "Nigerian"]),
        ("NI", &["Nicaragua", "Nicaraguan"]),
        ("NL", &["Netherlands", "Dutch"]),
        ("NO", &["Norway", "Norwegian"]),
        ("NP", &["Nepal", "Nepalese"]),
        ("NR", &["Nauru", "Nauruan"]),
        ("NU", &["Niue", "Niuean"]),
        ("NZ", &["New Zealand", "New Zealander"]),
        ("OM", &["Oman", "Omani"]),
        ("PA", &["Panama", "Panamanian"]),
        ("PE", &["Peru", "Peruvian"]),
        ("PF", &["French Polynesia", "French Polynesian"]),
        ("PG", &["Papua New Guinea", "Papua New Guinean"]),
        ("PH", &["Philippines", "Filipino"]),
        ("PK", &["Pakistan", "Pakistani"]),
        ("PL", &["Poland", "Polish"]),
        (
            "PM",
            &[
                "Saint Pierre & Miquelon",
                "Saint-Pierrais, Miquelonnais",
            ],
        ),
        ("PN", &["Pitcairn Islands", "Pitcairn", "Pitcairn Islander"]),
        ("PR", &["Puerto Rico", "Puerto Rican"]),
        (
            "PS",
            &[
                "Palestinian Territories",
                "Palestinian Territory, Occupied",
                "Palestine",
                "Palestinian",
            ],
        ),
        ("PT", &["Portugal", "Portuguese"]),
        ("PW", &["Palau", "Palauan"]),
        ("PY", &["Paraguay", "Paraguayan"]),
        ("QA", &["Qatar", "Qatari"]),
        ("RE", &["Réunion", "Reunion"]),
        ("RO", &["Romania", "Romanian"]),
        ("RS", &["Serbia", "Serbian"]),
        ("RU", &["Russia", "Russian Federation", "Russian"]),
        ("RW", &["Rwanda", "Rwandan"]),
        ("SA", &["Saudi Arabia", "Saudi Arabian"]),
        ("SB", &["Solomon Islands", "Solomon Islander"]),
        ("SC", &["Seychelles", "Seychellois"]),
        ("SD", &["Sudan", "Sudanese"]),
        ("SE", &["Sweden", "Swedish"]),
        ("SG", &["Singapore", "Singaporean"]),
        ("SH", &["Saint Helena", "Saint Helenian"]),
        ("SI", &["Slovenia", "Slovene"]),
        ("SJ", &["Svalbard & Jan Mayen"]),
        ("SK", &["Slovakia", "Slovak"]),
        ("SL", &["Sierra Leone", "Sierra Leonean"]),
        ("SM", &["San Marino", "Sammarinese"]),
        ("SN", &["Senegal", "Senegalese"]),
        ("SO", &["Somalia", "Somali"]),
        ("SR", &["Suriname", "Surinamer"]),
        ("SS", &["South Sudan", "South Sudanese"]),
        ("ST", &["São Tomé & Príncipe", "Sao Tomean"]),
        ("SV", &["El Salvador", "Salvadoran"]),
        ("SX", &["Sint Maarten", "Sint Maarten (Dutch part)"]),
        ("SY", &["Syria", "Syrian Arab Republic", "Syrian"]),
        ("SZ", &["Eswatini", "Swaziland", "Swazi"]),
        ("TA", &["Tristan da Cunha", "Tristanian"]),
        (
            "TC",
            &[
                "Turks & Caicos Islands",
                "Turks & Caicos Islander",
            ],
        ),
        ("TD", &["Chad", "Chadian"]),
        (
            "TF",
            &[
                "French Southern Territories",
                "French Southern Territory resident",
            ],
        ),
        ("TG", &["Togo", "Togolese"]),
        ("TH", &["Thailand", "Thai"]),
        ("TJ", &["Tajikistan", "Tadzhik"]),
        ("TK", &["Tokelau", "Tokelauan"]),
        ("TL", &["Timor-Leste", "East Timorese"]),
        ("TM", &["Turkmenistan", "Turkmen"]),
        ("TN", &["Tunisia", "Tunisian"]),
        ("TO", &["Tonga", "Tongan"]),
        ("TR", &["Türkiye", "Turkey", "Turkish"]),
        ("TT", &["Trinidad & Tobago", "Trinidadian"]),
        ("TV", &["Tuvalu", "Tuvaluan"]),
        ("TW", &["Taiwan", "Republic of China", "Taiwanese"]),
        ("TZ", &["Tanzania", "Tanzanian"]),
        ("UA", &["Ukraine", "Ukrainian"]),
        ("UG", &["Uganda", "Ugandan"]),
        (
            "UM",
            &[
                "U.S. Outlying Islands",
                "US Minor Outlying Islands",
                "United States Minor Outlying Islands",
            ],
        ),
        ("UN", &["United Nations", "UN member"]),
        ("US", &["United States", "USA", "American"]),
        ("UY", &["Uruguay", "Uruguayan"]),
        ("UZ", &["Uzbekistan", "Uzbekistani"]),
        (
            "VA",
            &["Vatican City", "Vatican", "Holy See (Vatican City State)"],
        ),
        (
            "VC",
            &[
                "Saint Vincent & the Grenadines",
                "Saint Vincentian",
            ],
        ),
        ("VE", &["Venezuela", "Venezuelan"]),
        ("VG", &["British Virgin Islands"]),
        (
            "VI",
            &[
                "U.S. Virgin Islands",
                "US Virgin Islands",
            ],
        ),
        ("VN", &["Vietnam", "Viet Nam", "Vietnamese"]),
        ("VU", &["Vanuatu", "Ni-Vanuatu"]),
        (
            "WF",
            &[
                "Wallis & Futuna",
                "Wallis and Futuna",
                "Wallis and Futuna Islander",
            ],
        ),
        ("WS", &["Samoa", "Samoan"]),
        ("XK", &["Kosovo", "Kosovar"]),
        ("YE", &["Yemen", "Yemeni"]),
        ("YT", &["Mayotte", "Mahoran"]),
        ("ZA", &["South Africa", "South African"]),
        ("ZM", &["Zambia", "Zambian"]),
        ("ZW", &["Zimbabwe", "Zimbabwean"]),
    ]
});

pub(crate) static COUNTRIES_CODE_MAP: Lazy<HashMap<&str, &Country>> = Lazy::new(|| {
    COUNTRIES
        .iter()
        .map(|country| (country.0, country))
        .collect()
});

pub(crate) static COUNTRIES_FLAG_MAP: Lazy<HashMap<String, &Country>> = Lazy::new(|| {
    use crate::code_to_flag_emoji;
    COUNTRIES
        .iter()
        .map(|country| (code_to_flag_emoji(country.0), country))
        .collect()
});
